import Head from 'next/head'
import Footer from "../molecules/Footer";
import Header from "../molecules/Header";
import Banner from "../molecules/Banner";
import { useArticles } from "../../context/articles";
import {
    main, 
    content, 
    contentBannerTop, 
    contentChildren, 
    spinner,
    app,
    contentBannerRight
} from '../../styles/Layout.module.css'

export default function Layout({children}) {

    const {state} = useArticles()

    return (
        <div className={app}>
            <Head>
                <title>Acumulado</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/laNacion.jpeg" />
            </Head>
            <Header />
            <div className={contentBannerTop}>
                <Banner />
            </div>
            <main className={main}>
                <div className={content}>
                    <div className={contentChildren}>
                        { !state.loading ? children : <div className={spinner} /> }
                    </div>
                    <div className={contentBannerRight}>
                        <Banner orientation='right' />
                    </div>
                </div>
            </main>
            <Footer />
        </div>
    )
}
